### ISSUE TITLE
cannot find cam by given deviceId in cam list

### ISSUE THREAD

**Issue by riyanpro** [PanoVideo/PanoVideoDemo#2]
npm run dev后，控制台报错：cannot find cam by given deviceId in cam list

**Comment by vanezhang** [comment]
你好，请问运行的是哪个Demo，可以复现么

**Comment by vanezhang** [comment]
你好 反馈已收到 我们处理下。

**Comment by Villee** [comment]
> npm run dev后，控制台报错：cannot find cam by given deviceId in cam list

已经修复，请pull最新版本试一下
